default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: yuri
  password: ilovepizza
  host: localhost

development:
  <<: *default
  database: capsdb_dev

test:
  <<: *default
  database: capsdb_test

